apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=Dockerfile"
        - "--context=dir://workspace"
        - "--destination=f0ssel/kaniko"
        - "--context=git://github.com/f0ssel/kaniko.git#refs/heads/master"
        - "--cache"
        - "--cache-repo=f0ssel/kaniko-cache"
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
      env:
        - name: GIT_TOKEN
          value: "ADD HERE"
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json