apiVersion: v1
kind: Pod
metadata:
  name: environment-$TIMESTAMP
spec:
  initContainers:
    - name: setup
      image: bitnami/git:latest
      command:
        - 'bash'
        - '-c'
        - |
          git clone --depth 1 https://github.com/$GITHUB_REPO.git /workspace

          mkdir -p /workspace/.coder/tmp
          echo -e "$DOCKERFILE_DATA" > /workspace/.coder/tmp/dockerfile
      volumeMounts:
        - name: repo
          mountPath: /workspace
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=.coder/tmp/dockerfile"
        - "--context=dir://workspace"
        - "--destination=$IMAGE:env-$TIMESTAMP"
        - "--cache"
        - "--cache-repo=$IMAGE-cache"
      volumeMounts:
        - name: repo
          mountPath: /workspace
        - name: kaniko-secret
          mountPath: /kaniko/.docker
  containers:
    - name: environment
      image: $IMAGE:env-$TIMESTAMP
      imagePullPolicy: Always
      command: ["tail"]
      args: [ "-f", "/dev/null" ]
  restartPolicy: Never
  volumes:
    - name: repo
      emptyDir: {}
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json